import { LandRegistryData } from "../../src/types";

export const mockLandRegistryData: LandRegistryData[] = [
  {
    "price": "91000",
    "date_of_transfer": "1995-07-21",
    "postcode": "B79 9HE",
    "property_type": "D",
    "old_new": "Y",
    "duration": "F",
    "paon": "2",
    "saon": "",
    "street": "CHURCHSIDE",
    "locality": "HARLASTON",
    "city": "TAMWORTH",
    "district": "LICHFIELD",
    "county": "STAFFORDSHIRE",
    "ppd_category_type": "A",
    "record_status": "A"
  },
  {
    "price": "47400",
    "date_of_transfer": "1995-07-13",
    "postcode": "NN4 8LP",
    "property_type": "S",
    "old_new": "N",
    "duration": "F",
    "paon": "256",
    "saon": "",
    "street": "TOWCESTER ROAD",
    "locality": "NORTHAMPTON",
    "city": "NORTHAMPTON",
    "district": "NORTHAMPTON",
    "county": "NORTHAMPTONSHIRE",
    "ppd_category_type": "A",
    "record_status": "A"
  },
  {
    "price": "57000",
    "date_of_transfer": "2005-08-03",
    "postcode": "CH45 9NF",
    "property_type": "F",
    "old_new": "N",
    "duration": "L",
    "paon": "MONTPELLIER HOUSE",
    "saon": "6",
    "street": "MONTPELLIER CRESCENT",
    "locality": "WALLASEY",
    "city": "WALLASEY",
    "district": "WIRRAL",
    "county": "MERSEYSIDE",
    "ppd_category_type": "A",
    "record_status": "A"
  },
];
